### ISSUE TITLE
How to collaborate?

### ISSUE THREAD

**Issue by milancurcic** [Fortran-FOSS-Programmers/Fortran-202X-Proposals#1]
What is the best way to collaborate using this repo? For example:

* Should a feature request be opened as an issue?
* Should a feature request be a markdown document submitted via pull request?

I like the issues approach as it allows discussion threads and upvoting.

**Comment by jacobwilliams** [comment]
Perhaps for each proposal:
* open an issue for discussion
* add a directory (containing a main markdown file which would be the final product, but it could also have other supporting files if necessary)

Collaboration can happen through branching, merge requests, etc., as well as discussion on the issue page.

We could also use the wiki in some way?

**Comment by zbeekman** [comment]
I think that issues are a good way to get started... then ideally produce some kind of markdown document per issue in advance of the meeting.
