### ISSUE TITLE
New Fortran Language Feature Proposal Template?

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/Fortran-202X-Proposals#2]
Need to create a template for what a proposal would look like. Probably needs to include "use cases". What is the format that the standards committee prefers?

**Comment by zbeekman** [comment]
@tclune @rouson Do you have any thoughts on this?

**Comment by wadudmiah** [comment]
How would you vectorise templated operations? From what I understand, widths of data types can only be determined at runtime or is this not the case? If templated operations can be vectorised, then this will definitely be a useful feature to have. A templated BLAS library could be written!

**Comment by szaghi** [comment]
Dear @wadudmiah 

maybe I am wrong, but I think that @jacobwilliams and @zbeekman were speaking about the *template* (textual formatting) to be used to submit our proposals to the standard committee. On the contrary your (very interesting) comment about *template* should be done into a dedicated proposal about *Fortran template*. Please, check the current opened issues (https://github.com/Fortran-FOSS-Programmers/Fortran-202X-Proposals/issues) and if there is not an issue already dealing with Fortran Template, feel free to open new one.

My best regards.

**Comment by tclune** [comment]
@zbeekman  Apologies for the slow response.   When I first read it, I did not have time to track down the context of the question.   The subsequent messages in the thread gave me sufficient context …

I don’t have any strong opinions, and am mostly waiting to see what the president of J3 wants.      Certainly creating a strawman template could be very useful.     At the moment, I don’t immediately see what I would want in such a template beyond something trivial, but a strawman could generate further thoughts.




On Jul 21, 2017, at 5:32 PM, zbeekman <notifications@github.com<mailto:notifications@github.com>> wrote:


@tclune<https://github.com/tclune> @rouson<https://github.com/rouson> Do you have any thoughts on this?

**Comment by tclune** [comment]
With regard to templates in the language ...  types would not be determined at _run_ time.    Everything must be resolved by the time the executable is created.    I believe that the approach in C++, is that a great deal of compilation is actually deferred until link time when the needed types are known.

**Comment by wadudmiah** [comment]
@tclune So if you created a template library, how would that work? There is definitely a need for template programming in Fortran which would do away with the need to have subroutines for different data types.

**Comment by szaghi** [comment]
@wadudmiah @tclune 

Can I suggest to open a new issue concerning Fortran template in the language? This one should be for the format of the proposals.

Cheers.

**Comment by zbeekman** [comment]
I took a stab at creating a *language feature proposal* template. See it at https://github.com/Fortran-FOSS-Programmers/Fortran-202X-Proposals/blob/master/.github/ISSUE_TEMPLATE.md

Contributions/hacks/criticism/PRs welcome.

I tried to encourage following the format of ftp://ftp.nag.co.uk/sc22wg5/N1951-N2000/N1972.pdf

If people think this is sufficient, let's close this issue.

**Comment by szaghi** [comment]
@zbeekman 

Thank you Zaak, your continuous, unstoppable work is priceless! For what it values, your skeleton looks good to me, but the most important opinions are the ones of committee members (yes Damian, I am thinking to you :smile: ).

Cheers

**Comment by tclune** [comment]
You need to remove the section about “Proposed syntax(es)”.

The plan is for subgroups to consolidate use cases and derive features/syntax.

- Tom




On Jul 26, 2017, at 11:29 AM, zbeekman <notifications@github.com<mailto:notifications@github.com>> wrote:


I took a stab at creating a template. See it at https://github.com/Fortran-FOSS-Programmers/Fortran-202X-Proposals/blob/master/.github/ISSUE_TEMPLATE.md

Contributions/hacks/criticism/PRs welcome.

I tried to encourage following the format of ftp://ftp.nag.co.uk/sc22wg5/N1951-N2000/N1972.pdf

If people think this is sufficient, let's close this issue.

**Comment by zbeekman** [comment]
Updated [template](https://github.com/Fortran-FOSS-Programmers/Fortran-202X-Proposals/blob/master/.github/ISSUE_TEMPLATE.md) to reflect what I think may be more consistent with @jacobwilliams' original thoughts and @tclune's input.

**Comment by zbeekman** [comment]
I move that we close this issue, now that https://github.com/Fortran-FOSS-Programmers/Fortran-202X-Proposals/blob/master/.github/ISSUE_TEMPLATE.md is here, unless anyone has additional ideas or concerns about the proposal in it's current form. I have copied the text here, below the horizontal rule, for convenience. Note that there are some un-rendered instructions as well included as html comments. Here is also a link to the raw text: https://raw.githubusercontent.com/Fortran-FOSS-Programmers/Fortran-202X-Proposals/master/.github/ISSUE_TEMPLATE.md which includes the instructions

---







# Proposal


# Use cases


# Rationale


# Examples



```Fortran
! Your code here
```

# Comments

**Comment by zbeekman** [comment]
Raw text included here for convenience:

---

    
    
    
    
    
    
    # Proposal
    

    # Use cases
    
    
    # Rationale
    
    
    # Examples
    
    
    
    ```Fortran
    ! Your code here
    ```
    
    # Comments

**Comment by milancurcic** [comment]
LGTM!

**Comment by zbeekman** [comment]
Closing, feel free to reopen if anyone thinks it needs tweaking, or better yet, just tweak or tweak+PR yourself! :-)
